# Generated by Django 5.0.6 on 2024-07-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citystreetshop', '0002_street_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citystreetshop.city'),
        ),
    ]
