# Generated by Django 5.0.6 on 2024-07-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citystreetshop', '0003_alter_street_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('building', models.CharField(max_length=100, verbose_name='Дом')),
                ('time_open', models.TimeField(verbose_name='Время открытия')),
                ('time_close', models.TimeField(verbose_name='Время закрытия')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citystreetshop.city')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citystreetshop.street')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
